baseURL = "https://resume.bernardes.eu/"
languageCode = "fr"
theme = "almeida-cv"
title = "Claudio Bernardes - CV"
DefaultContentLanguage = "fr"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#2b6cb0"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
