baseURL = "https://obsidienne.github.io/resume/"
languageCode = "fr"
theme = "almeida-cv"
title = "Claudio Bernardes - CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
