baseURL = "https://resume.bernardes.eu/"
languageCode = "fr"
theme = "almeida-cv"
title = "Claudio Bernardes - CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e53e3e"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
