baseURL = "https://resume.bernardes.eu/"
theme = "almeida-cv"
title = "Claudio Bernardes - CV"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[languages]
    [languages.en]
        title = "Claudio Bernardes - Resume"
        languageName = "English"
        languageCode = "en"
        weight = 1
    [languages.fr]
        title = "Claudio Bernardes - CV"
        languageName = "Français"
        languageCode = "fr"
        weight = 2

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#2b6cb0"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#666"
pages = 1
